hd <- read_csv("https://raw.githubusercontent.com/KimmoVehkalahti/Helsinki-Open-Data-Science/master/datasets/human_development.csv")
gii <- read_csv("https://raw.githubusercontent.com/KimmoVehkalahti/Helsinki-Open-Data-Science/master/datasets/gender_inequality.csv", na = "..")
lapply(list(hd,gii), dim)
lapply(list(hd,gii), summary)
lapply(list(hd,gii), names)
names(hd) <- c("HDI_rank", "Country", "HDI", "Life_Exp", "Edu_Exp", "Mean_school", "GNI", "GNI_minus_HDIR")
names(gii) <- c("GII_rank", "Country", "GII", "Mat_Mor", "Ado_Birth", "Parli_F", "Edu2_F", "Edu2_M", "Labo_F", "Labo_M")
gii <- gii %>% mutate("Edu2_FM" = Edu2_F/Edu2_M,
                      "Labo_FM" = Labo_F / Labo_M)
human <- inner_join(hd, gii, by = "Country")
write_csv(human, "human.csv")